Css two column layout
dcatan89/c1121-code-solutions pull request #20
Opened 2021-12-05 01:57 UTC by dcatan89

<img width="1062" alt="Screen Shot 2021-12-04 at 5 55 32 PM" src="https://user-images.githubusercontent.com/90487207/144730513-e58cd536-198d-416e-ab65-4140b8e52590.png">

2021-12-06 17:39 UTC, codingcodymiller requested changes
Hey Daniel! Nice start on this, I have some feedback about class names to get you started:

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="column-full second-row">
The class name `second-row` here gives very little insight into its purpose, you should try to make a more descriptive class name here.

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +    <div class="row bigrow">
The class name `bigrow` here gives very little insight into its purpose, you should try to make a more descriptive class name here. Additionally, class names that include multiple words should have the words separated by dashes, which is known as `kebab-case`.

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="tleft">
What does `tleft` mean?

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="column-half bleft">
`bleft`?

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="tright">
`tright`?

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +        <div class="column-half bright">
`bright`? Is it shiny?

2021-12-06 17:39 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="column-full last">
`last`? `last` what?

2021-12-06 19:07 UTC, dcatan89 commented
changed class names to be more descriptive

2021-12-07 23:35 UTC, codingcodymiller requested changes
These class names are definitely longer, but they don't describe their purpose at all. You should make the class name describe either what the content is (like a description of the contents of the element you are influencing such as `smart-software-section`) or a descriptor of what styling the class is actually doing if you are trying to create a reusable utility class.

2021-12-08 17:25 UTC, codingcodymiller requested changes

2021-12-08 17:25 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  display: flex;
I see you are using `display: flex` for each of these sections. When you are using layout classes to control your app layout, `display: flex` is usually an indicator that you need another `row`. You should put a `row` class element inside the `column` these classes are being applied to, then have additional `column` classes for the content inside that `row` It's always okay to have additional `row`s inside of a `column` class element 🤓

2021-12-09 20:36 UTC, codingcodymiller approved these changes
Nice work!!

2021-12-09 20:49 UTC, merged