Javascript functions practice
dcatan89/c1121-code-solutions pull request #32
Opened 2021-12-09 09:09 UTC by dcatan89

2021-12-09 20:30 UTC, codingcodymiller requested changes
Hey DJ! Please include a screenshot of all your tests passing, and send me a message on Slack when you have added it.

2021-12-09 20:38 UTC, dcatan89 commented
![Screen Shot 2021-12-09 at 12 36 26 PM](https://user-images.githubusercontent.com/90487207/145472116-9bbd5b16-ae58-4a67-ae72-19087bfdaef0.png)

2021-12-10 22:44 UTC, codingcodymiller requested changes

2021-12-10 22:44 UTC, codingcodymiller commented on javascript-functions-practice/get-description-of-person.js
> +  return person[propertyNames[0]] + ' ' + 'is a ' + person[propertyNames[1]] + ' ' + 'from ' + person[propertyNames[2]] + '.';
Why not just use the name of the properties?

2021-12-13 18:24 UTC, codingcodymiller approved these changes

2021-12-13 19:05 UTC, merged