Css ecommerce page
dcatan89/c1121-code-solutions pull request #35
Opened 2021-12-10 17:59 UTC by dcatan89

<img width="1074" alt="Screen Shot 2021-12-10 at 9 57 35 AM" src="https://user-images.githubusercontent.com/90487207/145620127-fe2396c1-26e8-4ec3-977d-99d3f1eb0e04.png">

2021-12-10 23:02 UTC, codingcodymiller requested changes
Hey DJ, there is too much vertical space between your lines of text as compared to the example, please revise.

2021-12-11 05:46 UTC, dcatan89 commented
<img width="1132" alt="Screen Shot 2021-12-10 at 9 42 27 PM" src="https://user-images.githubusercontent.com/90487207/145665677-7d64bd95-c7bc-4576-8145-f67484988cdc.png">

2021-12-13 18:26 UTC, codingcodymiller requested changes
Still too much space 👀 
![image](https://user-images.githubusercontent.com/32880187/145867691-e9bde791-05d7-4cad-a23c-40d1699f8170.png)

2021-12-13 19:05 UTC, dcatan89 commented
![Screen Shot 2021-12-13 at 11 03 31 AM](https://user-images.githubusercontent.com/90487207/145872596-5ad7c028-9d96-4748-b818-e5bbcfd44f76.png)

2021-12-14 00:50 UTC, codingcodymiller requested changes

2021-12-14 00:50 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +      <div class="column-full">
This column takes up only one fifth of the width, right? Why is it set as `column-full`? The rest of your columns are the same way, you should revise this to correctly describe its content.

2021-12-14 18:58 UTC, codingcodymiller requested changes

2021-12-14 18:58 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +          <div class="columnn-fifth width">
`width` is just setting this element to be full width, you should use `column-full` for that

2021-12-14 18:58 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +              </h4>
Your indentation needs to get fixed up here.

2021-12-14 18:58 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +            <span class="sizes-info font  lgrey-font"> One-size</span></h4>
Please move the closing tag for the `h4` to its own line

2021-12-14 18:58 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +          <div class="columnn-fifth width ">
`width` is just setting this element to be full width, you should use `column-full` for that

2021-12-14 22:59 UTC, codingcodymiller approved these changes

2021-12-14 23:00 UTC, merged