media queries completed
dcatan89/c1121-code-solutions pull request #49
Opened 2021-12-16 16:15 UTC by dcatan89

<img width="484" alt="Screen Shot 2021-12-16 at 8 11 20 AM" src="https://user-images.githubusercontent.com/90487207/146407953-bc44848a-f55e-4225-a27f-2c18f76b5caf.png">
<img width="460" alt="Screen Shot 2021-12-16 at 8 11 12 AM" src="https://user-images.githubusercontent.com/90487207/146407957-c6e4e508-12b8-4c0f-8350-3547e866005c.png">
![Kapture 2021-12-16 at 08 12 07](https://user-images.githubusercontent.com/90487207/146407979-4cb17b42-ceef-4922-8557-01a1b3aa4246.gif)
![Kapture 2021-12-16 at 08 14 46](https://user-images.githubusercontent.com/90487207/146408168-2bc244bb-c6c9-4bc0-977f-bfcadcec215e.gif)

2021-12-16 16:16 UTC, dcatan89 commented
![Kapture 2021-12-16 at 08 14 46](https://user-images.githubusercontent.com/90487207/146408257-987eb099-f111-412d-9e54-2717711c840d.gif)

2021-12-16 16:18 UTC, dcatan89 commented
![Kapture 2021-12-16 at 08 17 28](https://user-images.githubusercontent.com/90487207/146408690-b9071321-d665-492d-9868-b3213d190a79.gif)

2021-12-16 19:38 UTC, codingcodymiller requested changes

2021-12-16 19:38 UTC, codingcodymiller commented on css-media-queries/breakpoints.html
> +    }
Please fix your indentation.

2021-12-16 19:38 UTC, codingcodymiller commented on css-media-queries/at-media.html
> +}
Please fix your indentation.

2021-12-16 23:59 UTC, codingcodymiller requested changes

2021-12-16 23:59 UTC, codingcodymiller commented on css-media-queries/at-media.html
> +}
This is still not correct indentation.

2021-12-16 23:59 UTC, codingcodymiller commented on css-media-queries/breakpoints.html
> +    }
THis is still not correct indentation. Please follow the format taught in the documentation.

2021-12-27 18:27 UTC, codingcodymiller approved these changes

2021-12-27 18:49 UTC, merged