completed html-web-page-challenge
dcatan89/c1121-code-solutions pull request #8
Opened 2021-12-01 02:03 UTC by dcatan89

![Screen Shot 2021-11-30 at 6 01 59 PM](https://user-images.githubusercontent.com/90487207/144158328-54377086-5e52-43e3-874b-f2234ca2c89c.png)

2021-12-01 19:05 UTC, codingcodymiller requested changes
Hey DJ! Your indentation in this document is pretty all over the place, please revise to follow proper HTML formatting rules.

2021-12-01 19:56 UTC, dcatan89 commented
Made changes to reflect better html indentation.

2021-12-01 22:46 UTC, codingcodymiller requested changes

2021-12-01 22:46 UTC, codingcodymiller commented on html-web-page/index.html
> +        </tr>
This indentation is still a total mess.

2021-12-02 00:38 UTC, dcatan89 commented on html-web-page/index.html
> +        </tr>
Indentation has been fixed.

2021-12-02 18:13 UTC, codingcodymiller approved these changes
Great work!

2021-12-02 19:52 UTC, merged